name: Generate API Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install postman-to-openapi
      run: npm install -g postman-to-openapi
    
    - name: Create docs directory
      run: mkdir -p docs
    
    - name: Convert Postman to OpenAPI
      run: |
        p2o ./Kickbase.postman_collection.json -f ./docs/openapi.yaml
    
    - name: Install Redoc CLI
      run: npm install -g @redocly/cli
    
    - name: Generate HTML Documentation
      run: |
        redocly build-docs ./docs/openapi.yaml -o ./docs/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs