name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install postman-to-openapi
      run: npm install -g postman-to-openapi

    - name: Convert Postman Collection to OpenAPI
      run: |
        p2o ./docs/Kickbase.postman_collection.json -f ./docs/openapi.yaml
        
    - name: Add OpenAPI metadata
      run: |
        # Add any additional metadata or modifications to the OpenAPI spec
        cat > ./docs/openapi-header.yaml << 'EOL'
        openapi: 3.0.0
        info:
          title: Kickbase API Documentation
          version: 1.0.0
          description: |
            # Kickbase API Documentation
            Unofficial documentation of the Kickbase API.
            
            ## Competition IDs
            - 1: Bundesliga
            - 2: 2. Bundesliga
            - 3: La Liga
            - 4: Google Pixel Frauen Bundesliga
          contact:
            name: Kai Detmers
            url: https://github.com/t3mr0i/Kickbase-API
        servers:
          - url: https://api.kickbase.com
            description: Production Server
        EOL
        
        # Combine header with generated OpenAPI spec
        cat ./docs/openapi-header.yaml ./docs/openapi.yaml > ./docs/openapi.temp.yaml
        mv ./docs/openapi.temp.yaml ./docs/openapi.yaml
        rm -f ./docs/openapi-header.yaml

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs